/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-08 10:28:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/resources/client/./inc/preloader.jsp", Long.valueOf(1678271279795L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Environmental</title>\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("\n");
      out.write("    <!-- CSS here -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/progressbar_barfiller.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animated-headline.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- ? Preloader Start -->\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- ? Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <img src=\"assets/img/logo/loder.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Preloader Start -->");
      out.write("\n");
      out.write("    <!-- Preloader Start -->\n");
      out.write("    \n");
      out.write("    <header>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("        <!-- Header Start -->\n");
      out.write("        <div class=\"header-area\">\n");
      out.write("            <div class=\"main-header \">\n");
      out.write("                <div class=\"header-bottom  header-sticky\">\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("                        <div class=\"row align-items-center\">\n");
      out.write("                            <!-- Logo -->\n");
      out.write("                            <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                                <div class=\"logo\">\n");
      out.write("                                    <a href=\"index.html\"><img src=\"assets/img/logo/logo.png\" alt=\"\"></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                                <div class=\"menu-wrapper  d-flex align-items-center justify-content-end\">\n");
      out.write("                                    <!-- Main-menu -->\n");
      out.write("                                    <div class=\"main-menu d-none d-lg-block\">\n");
      out.write("                                        <nav>\n");
      out.write("                                            <ul id=\"navigation\">                                                                                          \n");
      out.write("                                                <li><a href=\"index.html\">Home</a></li>\n");
      out.write("                                                <li><a href=\"about.html\">About</a></li>\n");
      out.write("                                                <li><a href=\"what-do.html\">What we Do</a></li>\n");
      out.write("                                                <li><a href=\"projects.html\">Projects</a></li>\n");
      out.write("                                                <li><a href=\"blog.html\">Blog</a>\n");
      out.write("                                                    <ul class=\"submenu\">\n");
      out.write("                                                        <li><a href=\"blog.html\">Blog</a></li>\n");
      out.write("                                                        <li><a href=\"blog_details.html\">Blog Details</a></li>\n");
      out.write("                                                        <li><a href=\"elements.html\">Element</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </nav>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Header-btn -->\n");
      out.write("                                    <div class=\"header-right-btn d-none d-lg-block ml-20\">\n");
      out.write("                                        <a href=\"contact.html\" class=\"btn header-btn\">Make a Donation</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div> \n");
      out.write("                            <!-- Mobile Menu -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Header End -->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </header>\n");
      out.write("    <main>\n");
      out.write("        \n");
      out.write("        <!-- slider Area Start-->\n");
      out.write("        <div class=\"slider-area position-relative\">\n");
      out.write("            <div class=\"slider-active dot-style\">\n");
      out.write("                <!-- Single Slider -->\n");
      out.write("                <div class=\"single-slider hero-overly slider-height slider-bg1 d-flex align-items-center\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-xl-8 col-lg-8 col-md-8 col-sm-10\">\n");
      out.write("                                <div class=\"hero__caption\">\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".2s\">Environment</h1>\n");
      out.write("                                    <P data-animation=\"fadeInUp\" data-delay=\".4s\">Provide us a green and healthy life<br> we need to protect </P>\n");
      out.write("                                    <!-- Hero-btn -->\n");
      out.write("                                    <div class=\"hero__btn\">\n");
      out.write("                                        <a href=\"industries.html\" class=\"hero-btn mb-10\"  data-animation=\"fadeInUp\" data-delay=\".8s\">Join Us Now</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Single Slider -->\n");
      out.write("                <div class=\"single-slider hero-overly slider-height slider-bg1 d-flex align-items-center\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-xl-8 col-lg-8 col-md-8 col-sm-10\">\n");
      out.write("                                <div class=\"hero__caption\">\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".2s\">Environment</h1>\n");
      out.write("                                    <P data-animation=\"fadeInUp\" data-delay=\".4s\">Provide us a green and healthy life<br> we need to protect </P>\n");
      out.write("                                    <!-- Hero-btn -->\n");
      out.write("                                    <div class=\"hero__btn\">\n");
      out.write("                                        <a href=\"industries.html\" class=\"hero-btn mb-10\"  data-animation=\"fadeInUp\" data-delay=\".8s\">Join Us Now</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- Single Slider -->\n");
      out.write("                <div class=\"single-slider hero-overly slider-height slider-bg1 d-flex align-items-center\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-xl-8 col-lg-8 col-md-8 col-sm-10\">\n");
      out.write("                                <div class=\"hero__caption\">\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".2s\">Environment</h1>\n");
      out.write("                                    <P data-animation=\"fadeInUp\" data-delay=\".4s\">Provide us a green and healthy life<br> we need to protect </P>\n");
      out.write("                                    <!-- Hero-btn -->\n");
      out.write("                                    <div class=\"hero__btn\">\n");
      out.write("                                        <a href=\"industries.html\" class=\"hero-btn mb-10\"  data-animation=\"fadeInUp\" data-delay=\".8s\">Join Us Now</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--? video_start -->\n");
      out.write("            <div class=\"video-area d-flex align-items-center justify-content-center\">\n");
      out.write("                <div class=\"video-wrap position-relative\">\n");
      out.write("                    <div class=\"video-icon\" >\n");
      out.write("                        <a class=\"popup-video btn-icon\" href=\"https://www.youtube.com/watch?v=up68UAfH0d0\"><i class=\"fas fa-play\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- video_end -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- slider Area End-->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!--? Visit Our Tailor Start -->\n");
      out.write("        <div class=\"visit-tailor-area fix\">\n");
      out.write("            <!--Right Contents  -->\n");
      out.write("            <div class=\"tailor-offers\"></div>\n");
      out.write("            <!-- left Contents -->\n");
      out.write("            <div class=\"tailor-details\">\n");
      out.write("                <span>Our Mission</span>\n");
      out.write("                <h2>Our main goal is to protect animals</h2>\n");
      out.write("                <p>The automated process starts as soon as \n");
      out.write("                    your clothes go into the machine. Duis cursus, mi quis \n");
      out.write("                    viverra ornare, eros dolor interdum nulla, ut commodo \n");
      out.write("                    diam libero vitae erat. Aenean faucibus nibh et justo \n");
      out.write("                    cursus id rutrum lorem imperdiet. Nunc ut sem vitae \n");
      out.write("                risus tristique posuere.</p>\n");
      out.write("                <p class=\"pera-bottom\">Interdum nulla, ut commodo diam libero vitae erat. \n");
      out.write("                    Aenean faucibus nibh et justo cursus id rutrum lorem \n");
      out.write("                imperdiet. Nunc ut sem vitae risus tristique posuere.</p>\n");
      out.write("                <div class=\"footer-tittles\">\n");
      out.write("                    <p>CEO, Consulto</p>\n");
      out.write("                    <h2>Capcilena Hanry</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Visit Our Tailor End -->\n");
      out.write("        <!--? Services Area Start -->\n");
      out.write("        <div class=\"service-area section-padding30\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-11\">\n");
      out.write("                        <div class=\"single-cat text-center mb-30\">\n");
      out.write("                            <div class=\"cat-icon\">\n");
      out.write("                                <img src=\"assets/img/gallery/services1.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cat-cap\">\n");
      out.write("                                <h5><a href=\"#\">Clean Water</a></h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-11\">\n");
      out.write("                        <div class=\"single-cat active text-center mb-30\">\n");
      out.write("                            <div class=\"cat-icon\">\n");
      out.write("                                <img src=\"assets/img/gallery/services2.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cat-cap\">\n");
      out.write("                                <h5><a href=\"#\">Renewable energy</a></h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-11\">\n");
      out.write("                        <div class=\"single-cat text-center mb-30\">\n");
      out.write("                            <div class=\"cat-icon\">\n");
      out.write("                                <img src=\"assets/img/gallery/services3.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cat-cap\">\n");
      out.write("                                <h5><a href=\"#\">Protect animals</a></h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Services Area End -->\n");
      out.write("        <!--? About Area Start -->\n");
      out.write("        <section class=\"support-company-area fix pt-10\">\n");
      out.write("            <div class=\"support-wrapper align-items-center\">\n");
      out.write("                <div class=\"left-content\">\n");
      out.write("                    <!-- section tittle -->\n");
      out.write("                    <div class=\"section-tittle section-tittle2 mb-30\">\n");
      out.write("                        <span>Why You Should join us</span>\n");
      out.write("                        <h2>A lot of animals need protection</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"support-caption\">\n");
      out.write("                        <p class=\"pera-top\">Interdum nulla, ut commodo diam libero vitae erat. \n");
      out.write("                            Aenean faucibus nibh et justo cursus id rutrum lorem \n");
      out.write("                        imperdiet. Nunc ut sem vitae risus tristique posuere.</p>\n");
      out.write("                        <a href=\"#\" class=\"border-btn\">Join Us Now</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"right-content\">\n");
      out.write("                    <!-- img -->\n");
      out.write("                    <div class=\"right-img\">\n");
      out.write("                        <img src=\"assets/img/gallery/safe_in.png\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"support-img-cap text-center d-flex\">\n");
      out.write("                        <div class=\"single-one\">\n");
      out.write("                            <span>950</span>\n");
      out.write("                            <p>Poaching cases</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"single-two\">\n");
      out.write("                            <span>230</span>\n");
      out.write("                            <p>Volunteers worldwide</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- About Area End -->\n");
      out.write("        <!--? Our Cases Start -->\n");
      out.write("        <div class=\"our-cases-area section-padding30\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row justify-content-center\">\n");
      out.write("                    <div class=\"col-xl-10 col-lg-10 \">\n");
      out.write("                        <!-- Section Tittle -->\n");
      out.write("                        <div class=\"section-tittle text-center mb-80\">\n");
      out.write("                            <h2>Every day 6,000 beavers perished</h2>\n");
      out.write("                            <p class=\"pl-20 pr-20\">Interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo \n");
      out.write("                            cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-cases mb-40\">\n");
      out.write("                            <div class=\"cases-img\">\n");
      out.write("                                <img src=\"assets/img/gallery/case1.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cases-caption\">\n");
      out.write("                                <h3><a href=\"#\">Wildlife in Danger</a></h3>\n");
      out.write("                                <p>Interdum nulla, ut commodo diam libero vitae \n");
      out.write("                                    erat. Aenean faucibus nibh et justo cursus \n");
      out.write("                                rutrum.</p>\n");
      out.write("                                <!-- Progress Bar -->\n");
      out.write("                                <div class=\"single-skill mb-15\">\n");
      out.write("                                    <div class=\"bar-progress\">\n");
      out.write("                                        <div id=\"bar1\" class=\"barfiller\">\n");
      out.write("                                            <div class=\"tipWrap\">\n");
      out.write("                                                <span class=\"tip\"></span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <span class=\"fill\" data-percentage=\"70\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- / progress -->\n");
      out.write("                                <div class=\"prices\">\n");
      out.write("                                    <p><span>47,589 of 74,574</span></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-cases mb-40\">\n");
      out.write("                            <div class=\"cases-img\">\n");
      out.write("                                <img src=\"assets/img/gallery/case2.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cases-caption\">\n");
      out.write("                                <h3><a href=\"#\">Our Green Projects</a></h3>\n");
      out.write("                                <p>Interdum nulla, ut commodo diam libero vitae \n");
      out.write("                                    erat. Aenean faucibus nibh et justo cursus \n");
      out.write("                                rutrum.</p>\n");
      out.write("                                <!-- Progress Bar -->\n");
      out.write("                                <div class=\"single-skill mb-15\">\n");
      out.write("                                    <div class=\"bar-progress\">\n");
      out.write("                                        <div id=\"bar2\" class=\"barfiller\">\n");
      out.write("                                            <div class=\"tipWrap\">\n");
      out.write("                                                <span class=\"tip\"></span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <span class=\"fill\" data-percentage=\"25\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"prices\">\n");
      out.write("                                    <p><span>47,589 of 74,574</span></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-6\">\n");
      out.write("                        <div class=\"single-cases\">\n");
      out.write("                            <div class=\"cases-img\">\n");
      out.write("                                <img src=\"assets/img/gallery/case3.png\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"cases-caption\">\n");
      out.write("                                <h3><a href=\"#\">Wildlife in Danger</a></h3>\n");
      out.write("                                <p>Interdum nulla, ut commodo diam libero vitae \n");
      out.write("                                    erat. Aenean faucibus nibh et justo cursus \n");
      out.write("                                rutrum.</p>\n");
      out.write("                                <!-- Progress Bar -->\n");
      out.write("                                <div class=\"single-skill mb-15\">\n");
      out.write("                                    <div class=\"bar-progress\">\n");
      out.write("                                        <div id=\"bar3\" class=\"barfiller\">\n");
      out.write("                                            <div class=\"tipWrap\">\n");
      out.write("                                                <span class=\"tip\"></span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <span class=\"fill\" data-percentage=\"50\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"prices\">\n");
      out.write("                                    <p><span>47,589 of 74,574</span></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Our Cases End -->\n");
      out.write("        <!--? Blog Area Start -->\n");
      out.write("        <section class=\"home-blog-area pb-padding\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- Section Tittle -->\n");
      out.write("                <div class=\"row justify-content-center\">\n");
      out.write("                    <div class=\"col-xl-8 col-lg-9 col-md-11\">\n");
      out.write("                        <div class=\"section-tittle text-center mb-90\">\n");
      out.write("                            <h2>Latest news</h2>\n");
      out.write("                            <p>Interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo  cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-xl-6 col-lg-6 col-md-6\">\n");
      out.write("                        <div class=\"home-blog-single mb-30\">\n");
      out.write("                            <div class=\"blog-img-cap\">\n");
      out.write("                                <div class=\"blog-img\">\n");
      out.write("                                    <img src=\"assets/img/gallery/home-blog1.png\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"blog-cap\">\n");
      out.write("                                    <h3><a href=\"blog_details.html\">Leverage agile frameworks to provide a robust synopsis</a></h3>\n");
      out.write("                                    <p>The automated process starts as soon as  your clothes go into the machine. Duis cursus, mi quis viverra ornare.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xl-6 col-lg-6 col-md-6\">\n");
      out.write("                        <div class=\"home-blog-single mb-30\">\n");
      out.write("                            <div class=\"blog-img-cap\">\n");
      out.write("                                <div class=\"blog-img\">\n");
      out.write("                                    <img src=\"assets/img/gallery/home-blog2.png\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"blog-cap\">\n");
      out.write("                                    <h3><a href=\"blog_details.html\">Leverage agile frameworks to provide a robust synopsis</a></h3>\n");
      out.write("                                    <p>The automated process starts as soon as  your clothes go into the machine. Duis cursus, mi quis viverra ornare.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Blog Area End -->\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"footer-wrapper\">\n");
      out.write("           <!-- Footer Start-->\n");
      out.write("           <div class=\"footer-area footer-padding\">\n");
      out.write("               <div class=\"container \">\n");
      out.write("                   <div class=\"row justify-content-between\">\n");
      out.write("                       <div class=\"col-xl-4 col-lg-3 col-md-8 col-sm-8\">\n");
      out.write("                           <div class=\"single-footer-caption mb-50\">\n");
      out.write("                               <div class=\"single-footer-caption mb-30\">\n");
      out.write("                                   <!-- logo -->\n");
      out.write("                                   <div class=\"footer-logo mb-35\">\n");
      out.write("                                       <a href=\"index.html\"><img src=\"assets/img/logo/logo2_footer.png\" alt=\"\"></a>\n");
      out.write("                                   </div>\n");
      out.write("                                   <div class=\"footer-tittle\">\n");
      out.write("                                       <div class=\"footer-pera\">\n");
      out.write("                                           <p>The automated process starts as soon as your clothes go into the machine.</p>\n");
      out.write("                                       </div>\n");
      out.write("                                   </div>\n");
      out.write("                                   <!-- social -->\n");
      out.write("                                   <div class=\"footer-social\">\n");
      out.write("                                       <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                                       <a href=\"https://bit.ly/sai4ull\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                                       <a href=\"#\"><i class=\"fab fa-pinterest-p\"></i></a>\n");
      out.write("                                   </div>\n");
      out.write("                               </div>\n");
      out.write("                           </div>\n");
      out.write("                       </div>\n");
      out.write("                       <div class=\"col-xl-2 col-lg-3 col-md-4 col-sm-4\">\n");
      out.write("                           <div class=\"single-footer-caption mb-50\">\n");
      out.write("                               <div class=\"footer-tittle\">\n");
      out.write("                                   <h4>Our solutions</h4>\n");
      out.write("                                   <ul>\n");
      out.write("                                       <li><a href=\"#\">Design & creatives</a></li>\n");
      out.write("                                       <li><a href=\"#\">Telecommunication</a></li>\n");
      out.write("                                       <li><a href=\"#\">Restaurant</a></li>\n");
      out.write("                                       <li><a href=\"#\">Programing</a></li>\n");
      out.write("                                       <li><a href=\"#\">Architecture</a></li>\n");
      out.write("                                   </ul>\n");
      out.write("                               </div>\n");
      out.write("                           </div>\n");
      out.write("                       </div>\n");
      out.write("                       <div class=\"col-xl-2 col-lg-2 col-md-4 col-sm-4\">\n");
      out.write("                           <div class=\"single-footer-caption mb-50\">\n");
      out.write("                               <div class=\"footer-tittle\">\n");
      out.write("                                   <h4>Company</h4>\n");
      out.write("                                   <ul>\n");
      out.write("                                       <li><a href=\"#\">About</a></li>\n");
      out.write("                                       <li><a href=\"#\">Review</a></li>\n");
      out.write("                                       <li><a href=\"#\">Insights</a></li>\n");
      out.write("                                       <li><a href=\"#\">Carrier</a></li>\n");
      out.write("                                   </ul>\n");
      out.write("                               </div>\n");
      out.write("                           </div>\n");
      out.write("                       </div>\n");
      out.write("                       <div class=\"col-xl-3 col-lg-4 col-md-6 col-sm-4\">\n");
      out.write("                           <div class=\"single-footer-caption mb-50\">\n");
      out.write("                               <div class=\"footer-tittle\">\n");
      out.write("                                   <h4>Contact us</h4>\n");
      out.write("                                   <ul>\n");
      out.write("                                       <li><a href=\"#\">consulto98@gmail.com</a></li>\n");
      out.write("                                       <li><a href=\"#\">76/A, Green road, NYC</a></li>\n");
      out.write("                                       <li><a href=\"#\">Privacy Policy</a></li>\n");
      out.write("                                       <li class=\"number\"><a href=\"#\">(80) 783 367-3904</a></li>\n");
      out.write("                                   </ul>\n");
      out.write("                               </div>\n");
      out.write("                           </div>\n");
      out.write("                       </div>\n");
      out.write("                   </div>\n");
      out.write("               </div>\n");
      out.write("           </div>\n");
      out.write("           <!-- footer-bottom area -->\n");
      out.write("           <div class=\"footer-bottom-area\">\n");
      out.write("               <div class=\"container\">\n");
      out.write("                   <div class=\"footer-border\">\n");
      out.write("                       <div class=\"row d-flex align-items-center\">\n");
      out.write("                           <div class=\"col-xl-12 \">\n");
      out.write("                               <div class=\"footer-copy-right text-center\">\n");
      out.write("                                   <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                                      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\n");
      out.write("                                  </div>\n");
      out.write("                              </div>\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("              <!-- Footer End-->\n");
      out.write("          </div>\n");
      out.write("      </footer>\n");
      out.write("      <!-- Scroll Up -->\n");
      out.write("      <div id=\"back-top\" >\n");
      out.write("        <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- JS here -->\n");
      out.write("\n");
      out.write("    <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\n");
      out.write("    <!-- Jquery, Popper, Bootstrap -->\n");
      out.write("    <script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/popper.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- Jquery Mobile Menu -->\n");
      out.write("    <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("    <script src=\"./assets/js/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/slick.min.js\"></script>\n");
      out.write("    <!-- One Page, Animated-HeadLin -->\n");
      out.write("    <script src=\"./assets/js/wow.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/animated.headline.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Date Picker -->\n");
      out.write("    <script src=\"./assets/js/gijgo.min.js\"></script>\n");
      out.write("    <!-- Nice-select, sticky -->\n");
      out.write("    <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.sticky.js\"></script>\n");
      out.write("    <!-- Progress -->\n");
      out.write("    <script src=\"./assets/js/jquery.barfiller.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- counter , waypoint,Hover Direction -->\n");
      out.write("    <script src=\"./assets/js/jquery.counterup.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/waypoints.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.countdown.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/hover-direction-snake.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- contact js -->\n");
      out.write("    <script src=\"./assets/js/contact.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.form.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.validate.min.js\"></script>\n");
      out.write("    <script src=\"./assets/js/mail-script.js\"></script>\n");
      out.write("    <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Jquery Plugins, main Jquery -->	\n");
      out.write("    <script src=\"./assets/js/plugins.js\"></script>\n");
      out.write("    <script src=\"./assets/js/main.js\"></script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
