/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-24 00:32:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.edu.springshop.domain.Category;
import java.util.List;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/sidebar_right.jsp", Long.valueOf(1676961898348L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/preloader.jsp", Long.valueOf(1676964235138L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/footer.jsp", Long.valueOf(1676961898300L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/header_link.jsp", Long.valueOf(1676964270175L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/navbar.jsp", Long.valueOf(1676964235135L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/sidebar_left.jsp", Long.valueOf(1678271620494L));
    _jspx_dependants.put("/WEB-INF/views/admin/product/../inc/footer_link.jsp", Long.valueOf(1677053266232L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.edu.springshop.domain.Category");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<Category> categoryList = (List)request.getAttribute("categoryList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>AdminLTE 3 | Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font: Source Sans Pro -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n");
      out.write("<!-- iCheck -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("<!-- JQVMap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/jqvmap/jqvmap.min.css\">\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/dist/css/adminlte.min.css\">\r\n");
      out.write("<!-- overlayScrollbars -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n");
      out.write("<!-- Daterange picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!-- summernote -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- React -->\r\n");
      out.write("<script src=\"https://unpkg.com/react@18/umd/react.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/react-dom@18/umd/react-dom.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/@babel/standalone/babel.min.js\"></script>\r\n");
      out.write("<!-- Vue -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".box-style{\r\n");
      out.write("	width:90px;\r\n");
      out.write("	height:95px;\r\n");
      out.write("	border:1px solid #ccc;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	margin:5px;\r\n");
      out.write("}\r\n");
      out.write(".box-style img{\r\n");
      out.write("	width:75px;\r\n");
      out.write("	height:70px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Preloader -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"preloader flex-column justify-content-center align-items-center\">\r\n");
      out.write("    <img class=\"animation__shake\" src=\"/resources/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTELogo\" height=\"60\" width=\"60\">\r\n");
      out.write(" </div>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write(" <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"index3.html\" class=\"nav-link\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- Navbar Search -->\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"navbar-search\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-search\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"navbar-search-block\">\r\n");
      out.write("          <form class=\"form-inline\">\r\n");
      out.write("            <div class=\"input-group input-group-sm\">\r\n");
      out.write("              <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("              <div class=\"input-group-append\">\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("                  <i class=\"fas fa-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"button\" data-widget=\"navbar-search\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <!-- Messages Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-comments\"></i>\r\n");
      out.write("          <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/resources/admin/dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Brad Diesel\r\n");
      out.write("                  <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/resources/admin/dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  John Pierce\r\n");
      out.write("                  <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"/resources/admin/dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Nora Silvester\r\n");
      out.write("                  <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Notifications Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-bell\"></i>\r\n");
      out.write("          <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <span class=\"dropdown-item dropdown-header\">15 Notifications</span>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"fullscreen\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-expand-arrows-alt\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"control-sidebar\" data-controlsidebar-slide=\"true\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Main Sidebar Container -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("	<!-- Brand Logo -->\r\n");
      out.write("	<a href=\"index3.html\" class=\"brand-link\"> <img\r\n");
      out.write("		src=\"/resources/admin/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\"\r\n");
      out.write("		class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("		<span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("	</a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Sidebar -->\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<!-- Sidebar user panel (optional) -->\r\n");
      out.write("		<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("			<div class=\"image\">\r\n");
      out.write("				<img src=\"/resources/admin/dist/img/user2-160x160.jpg\"\r\n");
      out.write("					class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"info\">\r\n");
      out.write("\r\n");
      out.write("				<a href=\"#\" class=\"d-block\">");
      out.print("zino");
      out.write("</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- SidebarSearch Form -->\r\n");
      out.write("		<div class=\"form-inline\">\r\n");
      out.write("			<div class=\"input-group\" data-widget=\"sidebar-search\">\r\n");
      out.write("				<input class=\"form-control form-control-sidebar\" type=\"search\"\r\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("				<div class=\"input-group-append\">\r\n");
      out.write("					<button class=\"btn btn-sidebar\">\r\n");
      out.write("						<i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Sidebar Menu -->\r\n");
      out.write("		<nav class=\"mt-2\">\r\n");
      out.write("			<ul class=\"nav nav-pills nav-sidebar flex-column\"\r\n");
      out.write("				data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library \r\n");
      out.write("               nav-item menu-open : 네비게이션 열려있게 해줌\r\n");
      out.write("               -->\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							상점관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							상품관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"/admin/category/main\"\r\n");
      out.write("							class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>상품관리</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"/admin/product/registform\"\r\n");
      out.write("							class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>상품등록</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>일괄등록</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							회원관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							주문관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							통계관리 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link active\"> <i\r\n");
      out.write("						class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("						<p>\r\n");
      out.write("							고객센터 <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"nav nav-treeview\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index.html\"\r\n");
      out.write("							class=\"nav-link active\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v1</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v2</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("								<i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("								<p>Dashboard v3</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- /.sidebar-menu -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /.sidebar -->\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("		<div class=\"content-wrapper\">\r\n");
      out.write("			<!-- Content Header (Page header) -->\r\n");
      out.write("			<div class=\"content-header\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row mb-2\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<h1 class=\"m-0\">상품등록</h1>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /.col -->\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("								<li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li class=\"breadcrumb-item active\">상품관리> 상품등록</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /.col -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.row -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.container-fluid -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.content-header -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Main content -->\r\n");
      out.write("			<section class=\"content\" id=\"app1\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("				\r\n");
      out.write("					<!-- Main row -->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col\">\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<select class=\"form-control\" name=\"category_idx\">\r\n");
      out.write("										<option value=\"0\">카테고리 선택</option>\r\n");
      out.write("										");
for(Category category : categoryList){ 
      out.write("\r\n");
      out.write("										<option value=\"");
      out.print(category.getCategory_idx());
      out.write('"');
      out.write('>');
      out.print(category.getCategory_name() );
      out.write("</option>\r\n");
      out.write("										");
} 
      out.write("\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>							\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"product_name\" placeholder=\"상품명\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"brand\" placeholder=\"브랜드명\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<input type=\"number\" class=\"form-control\" name=\"price\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>					\r\n");
      out.write("									\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<input type=\"number\" class=\"form-control\" name=\"discount\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("								\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<input type=\"file\" class=\"form-control\" name=\"file\" multiple>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<template v-for=\"json in imageList\">\r\n");
      out.write("										<imagebox :key=\"json.key\" :obj=\"json\"/>\r\n");
      out.write("									</template>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<textarea class=\"form-control\" id=\"detail\" name=\"detail\"></textarea>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("														\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-danger\" id=\"bt_regist\">등록</button>\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-danger\" id=\"bt_list\">목록</button>									\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>							\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.row (main row) -->\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- /.container-fluid -->\r\n");
      out.write("			\r\n");
      out.write("			</section>\r\n");
      out.write("			<!-- /.content -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.content-wrapper -->\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<footer class=\"main-footer\">\r\n");
      out.write("	<strong>Copyright &copy; 2014-2021 <a\r\n");
      out.write("		href=\"https://adminlte.io\">AdminLTE.io</a>.\r\n");
      out.write("	</strong> All rights reserved.\r\n");
      out.write("	<div class=\"float-right d-none d-sm-inline-block\">\r\n");
      out.write("		<b>Version</b> 3.2.0\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<!-- Control Sidebar -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("	<!-- Control sidebar content goes here -->\r\n");
      out.write("	여기가 우측 서랍장\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("		<!-- /.control-sidebar -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ./wrapper -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<!-- jQuery UI 1.11.4 -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("	<script>\r\n");
      out.write("		//$.widget.bridge('uibutton', $.ui.button)\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- Bootstrap 4 -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- ChartJS -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<!-- Sparkline -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/sparklines/sparkline.js\"></script>\r\n");
      out.write("	<!-- JQVMap -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jqvmap/jquery.vmap.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\r\n");
      out.write("	<!-- jQuery Knob Chart -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery-knob/jquery.knob.min.js\"></script>\r\n");
      out.write("	<!-- daterangepicker -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/admin/plugins/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/resources/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("	<!-- Summernote -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	<!-- overlayScrollbars -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/resources/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\r\n");
      out.write("	<!-- AdminLTE App -->\r\n");
      out.write("	<script src=\"/resources/admin/dist/js/adminlte.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE for demo purposes -->\r\n");
      out.write("	<!-- 	<script src=\"/resources/admin/dist/js/demo.js\"></script> -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("	<!-- <script src=\"/resources/admin/dist/js/pages/dashboard.js\"></script> -->");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		let app1;\r\n");
      out.write("		let key=0;\r\n");
      out.write("		\r\n");
      out.write("		const imagebox={\r\n");
      out.write("			template:`\r\n");
      out.write("				<div class=\"box-style\">\r\n");
      out.write("					<div v-on:click=\"del(json)\">X</div>\r\n");
      out.write("					<img :src=\"json.binary\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			`,\r\n");
      out.write("			props:[\"obj\"],\r\n");
      out.write("			data(){\r\n");
      out.write("				return{\r\n");
      out.write("					json:this.obj\r\n");
      out.write("				};\r\n");
      out.write("			},\r\n");
      out.write("			methods:{\r\n");
      out.write("				del(json){\r\n");
      out.write("					//alert(\"삭제할래?\");\r\n");
      out.write("					console.log(\"선택한 이미지에 대한 json은 \", json);\r\n");
      out.write("					\r\n");
      out.write("					//선택한 이미지에 대한 json이 배열에 있는지\r\n");
      out.write("					//없으면 -1, 있으면 0 이상의 수 (즉 발견된 index 번째)\r\n");
      out.write("					let index=app1.imageList.indexOf(json);  \r\n");
      out.write("					console.log(\"index is \", index);\r\n");
      out.write("					\r\n");
      out.write("					//Vue는 데이터만 지워도  UI가 반응을 보임 (즉, 자동으로 동기화) bind 되어 있음\r\n");
      out.write("					app1.imageList.splice(index, 1);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		app1=new Vue({\r\n");
      out.write("			el:\"#app1\",\r\n");
      out.write("			components:{\r\n");
      out.write("				imagebox\r\n");
      out.write("			},\r\n");
      out.write("			data:{\r\n");
      out.write("				count:5,\r\n");
      out.write("				imageList:[]  //files(read only) 배열의 정보를  담아놓을 배열\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		/*------------------------------------------\r\n");
      out.write("		중복된 이미지체크\r\n");
      out.write("		------------------------------------------*/\r\n");
      out.write("		function checkDuplicate(filename){\r\n");
      out.write("			let count=0;\r\n");
      out.write("			\r\n");
      out.write("			for(let i=0;i<app1.imageList.length;i++){\r\n");
      out.write("				let json=app1.imageList[i];\r\n");
      out.write("				if(json.name==filename){ //중복발견..\r\n");
      out.write("					count++;\r\n");
      out.write("					break;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			return count;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/*------------------------------------------\r\n");
      out.write("		미리보기\r\n");
      out.write("		------------------------------------------*/\r\n");
      out.write("		function preview(files){\r\n");
      out.write("			\r\n");
      out.write("			//이미지 화면에 출력\r\n");
      out.write("			for(let i=0;i<files.length;i++){\r\n");
      out.write("				let file = files[i];\r\n");
      out.write("				\r\n");
      out.write("				if(checkDuplicate(file.name) <1){ //중복된 이미지가 없을때만...\r\n");
      out.write("					let reader = new FileReader();//스트림 생성\r\n");
      out.write("					reader.onload=(e)=>{\r\n");
      out.write("						\r\n");
      out.write("						key++; //사용자가 이미지를 선택할때마다 1씩 증가하여 중복을 불허한다\r\n");
      out.write("						\r\n");
      out.write("						let json=[]; // imageList배열에 복합적인 정보를 담아놓기 위해 \r\n");
      out.write("						json['key']=key;//추후 이미지 삭제시 기준값으로 사용예정 \r\n");
      out.write("						json['name']=file.name; //중복이미지가 추가되지 않도록... \r\n");
      out.write("						json['binary']=e.target.result; //src에 대입할 바이너리 정보 \r\n");
      out.write("						json['file']=file; //전송할때 파라미터에 심을 파일\r\n");
      out.write("						\r\n");
      out.write("						app1.imageList.push(json);\r\n");
      out.write("					};\r\n");
      out.write("					reader.readAsDataURL(file);//파일읽기\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/*------------------------------------------\r\n");
      out.write("		등록\r\n");
      out.write("		------------------------------------------*/\r\n");
      out.write("		function regist(){\r\n");
      out.write("			//비동기 전송\r\n");
      out.write("			//파일업로드를 커스터마이징 시켰기 때문에...\r\n");
      out.write("			let formData = new FormData();\r\n");
      out.write("			\r\n");
      out.write("			formData.append(\"category.category_idx\", $(\"select[name='category_idx']\").val());\r\n");
      out.write("			formData.append(\"product_name\", $(\"input[name='product_name']\").val());\r\n");
      out.write("			formData.append(\"brand\", $(\"input[name='brand']\").val());\r\n");
      out.write("			formData.append(\"price\", $(\"input[name='price']\").val());\r\n");
      out.write("			formData.append(\"discount\", $(\"input[name='discount']\").val());\r\n");
      out.write("			formData.append(\"detail\", $(\"textarea[name='detail']\").val());\r\n");
      out.write("			\r\n");
      out.write("			//선택한 이미지 수만큼  formData 에 추가 \r\n");
      out.write("			for(let i=0;i<app1.imageList.length;i++){\r\n");
      out.write("				let json=app1.imageList[i];\r\n");
      out.write("				formData.append(\"photo\", json.file);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/admin/rest/product\", \r\n");
      out.write("				type:\"post\", \r\n");
      out.write("				data:formData, \r\n");
      out.write("				processData:false, /*query string 사용여부*/\r\n");
      out.write("				contentType:false, /* application/x-www-form~~ 사용여부*/\r\n");
      out.write("				success:function(result, status, xhr){\r\n");
      out.write("					console.log(result);\r\n");
      out.write("					alert(result.msg);\r\n");
      out.write("				},\r\n");
      out.write("				error:function(xhr, status, err){\r\n");
      out.write("					console.log(\"xhr\", xhr);\r\n");
      out.write("					console.log(\"status\", status);\r\n");
      out.write("					console.log(\"err\", err);\r\n");
      out.write("					\r\n");
      out.write("					//JSON.stringify()   json --> string 바꾼 이유? 문자열로 전송하기 위해\r\n");
      out.write("					let json=JSON.parse(xhr.responseText);  //string --> json\r\n");
      out.write("					alert(json.msg);\r\n");
      out.write("				}\r\n");
      out.write("			});		\r\n");
      out.write("		}		\r\n");
      out.write("		//서머노트 적용하기 \r\n");
      out.write("		$(function(){\r\n");
      out.write("			$(\"#detail\").summernote({\r\n");
      out.write("				height:200\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//파일에 이벤트 연결 \r\n");
      out.write("			$(\"input[name='file']\").change(function(){\r\n");
      out.write("				console.log(this.files);\r\n");
      out.write("				preview(this.files);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//등록 이벤트 연결 \r\n");
      out.write("			$(\"#bt_regist\").click(function(){\r\n");
      out.write("				regist();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//등록 이벤트 연결 \r\n");
      out.write("			$(\"#bt_list\").click(function(){\r\n");
      out.write("				location.href=\"/admin/product/list\";\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
