/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-02 00:46:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/admin/login/../inc/footer_link.jsp", Long.valueOf(1677053266232L));
    _jspx_dependants.put("/WEB-INF/views/admin/login/../inc/header_link.jsp", Long.valueOf(1676964270175L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>AdminLTE 3 | Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font: Source Sans Pro -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n");
      out.write("<!-- iCheck -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("<!-- JQVMap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/jqvmap/jqvmap.min.css\">\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/dist/css/adminlte.min.css\">\r\n");
      out.write("<!-- overlayScrollbars -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n");
      out.write("<!-- Daterange picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/admin/plugins/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!-- summernote -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/admin/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- React -->\r\n");
      out.write("<script src=\"https://unpkg.com/react@18/umd/react.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/react-dom@18/umd/react-dom.development.js\" crossorigin></script>\r\n");
      out.write("<script src=\"https://unpkg.com/@babel/standalone/babel.min.js\"></script>\r\n");
      out.write("<!-- Vue -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition\">\r\n");
      out.write("	<div class=\"wrapper p-5\">\r\n");
      out.write("		<!-- 로그인 폼  Card Begin -->\r\n");
      out.write("		<div class=\"card card-info\">\r\n");
      out.write("		    <div class=\"card-header\">\r\n");
      out.write("		        <h3 class=\"card-title\">관리자 로그인</h3>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <!-- /.card-header -->\r\n");
      out.write("		    <!-- form start -->\r\n");
      out.write("		    <form class=\"form-horizontal\" id=\"form1\">\r\n");
      out.write("		        <div class=\"card-body\">\r\n");
      out.write("		            <div class=\"form-group row\">\r\n");
      out.write("		                <div class=\"col\">\r\n");
      out.write("		                    <input type=\"text\" class=\"form-control\" placeholder=\"관리자 ID\" name=\"admin_id\">\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		            <div class=\"form-group row\">\r\n");
      out.write("		                <div class=\"col\">\r\n");
      out.write("		                    <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"admin_pass\">\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        <!-- /.card-body -->\r\n");
      out.write("		        <div class=\"card-footer\">\r\n");
      out.write("		            <button type=\"button\" id=\"bt_loginasync\" class=\"btn btn-info\">비동기 Login</button>\r\n");
      out.write("		            <button type=\"button\" id=\"bt_login\" class=\"btn btn-info\">동기 Login</button>\r\n");
      out.write("		            <button type=\"button\" class=\"btn btn-default float-right\">Cancel</button>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        <!-- /.card-footer -->\r\n");
      out.write("		    </form>\r\n");
      out.write("		</div>		\r\n");
      out.write("		<!-- 로그인 폼  Card End -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ./wrapper -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<!-- jQuery UI 1.11.4 -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("	<script>\r\n");
      out.write("		//$.widget.bridge('uibutton', $.ui.button)\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- Bootstrap 4 -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- ChartJS -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/chart.js/Chart.min.js\"></script>\r\n");
      out.write("	<!-- Sparkline -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/sparklines/sparkline.js\"></script>\r\n");
      out.write("	<!-- JQVMap -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jqvmap/jquery.vmap.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\r\n");
      out.write("	<!-- jQuery Knob Chart -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/jquery-knob/jquery.knob.min.js\"></script>\r\n");
      out.write("	<!-- daterangepicker -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"/resources/admin/plugins/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/resources/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("	<!-- Summernote -->\r\n");
      out.write("	<script src=\"/resources/admin/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	<!-- overlayScrollbars -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/resources/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\r\n");
      out.write("	<!-- AdminLTE App -->\r\n");
      out.write("	<script src=\"/resources/admin/dist/js/adminlte.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE for demo purposes -->\r\n");
      out.write("	<!-- 	<script src=\"/resources/admin/dist/js/demo.js\"></script> -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("	<!-- <script src=\"/resources/admin/dist/js/pages/dashboard.js\"></script> -->");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		//비동기 방식 로그인\r\n");
      out.write("		function loginAsync(){\r\n");
      out.write("			let formData=$(\"#form1\").serialize();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/admin/rest/login/admin\",\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				data:formData,\r\n");
      out.write("				success:function(result, status, xhr){\r\n");
      out.write("					alert(result.msg);\r\n");
      out.write("					location.href=\"/admin/main\"; //관리자 메인 요청\r\n");
      out.write("				},\r\n");
      out.write("				error:function(xhr, status, err){\r\n");
      out.write("					let json=JSON.parse(xhr.responseText);\r\n");
      out.write("					alert(json.msg);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//동기 방식 로그인 요청\r\n");
      out.write("		function login(){\r\n");
      out.write("			$(\"#form1\").attr({\r\n");
      out.write("				action:\"/admin/login\",\r\n");
      out.write("				method:\"post\"\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#form1\").submit();\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		$(function(){\r\n");
      out.write("			//비동기 로그인\r\n");
      out.write("			$(\"#bt_loginasync\").click(function(){\r\n");
      out.write("				loginAsync();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//동기 로그인\r\n");
      out.write("			$(\"#bt_login\").click(function(){\r\n");
      out.write("				login();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
